### ISSUE TITLE
Images are prefixed with '/' char 

### ISSUE THREAD

**Issue by tarunmenon95** [theonestack/hl-component-ecs-task#14]
Config:
```yaml
task_definition:
  nginx:
    image: nginx
    ports:
      - 80

```

Output:
```yaml
  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
      - Name: nginx
        Image:
          Fn::Join:
          - ''
          - - Fn::Sub: "/nginx"
            - ":"
            - latest
```
